name: Playwright Tests - CardMarket

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Installer les dépendances
        run: npm install

      - name: Installer Playwright et les navigateurs
        run: npx playwright install --with-deps

      - name: Lancer les tests Playwright
        run: npm test